services:
  backend:
    image: awesome-backend:latest
    build: backend/.
    ports:
      - "3000:81"
  db:
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  frontend:
    image: awesome-frontend:latest
    build: frontend/.
    ports:
      - "5173:80"

volumes:
  db_data:
