name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%dT%H%M%S")"

      # TODO: rationalise these outputs, remove duplication of repository name
      - name: Get Frontend tag
        id: fe_tag
        run: echo "::set-output name=fe_tag::fe_dev_ops_basics:main-${{ steps.timestamp.outputs.timestamp }}"

      - name: Get Backend tag
        id: be_tag
        run: echo "::set-output name=be_tag::be_dev_ops_basics:main-${{ steps.timestamp.outputs.timestamp }}"

      - name: Build frontend
        run: |
          cd frontend
          docker build -t 681666088935.dkr.ecr.eu-west-1.amazonaws.com/${RELEASE_NAME} .
          docker images
        env:
          RELEASE_NAME: ${{ steps.fe_tag.outputs.fe_tag }}

      - name: Build backend
        run: |
          cd backend
          docker build -t 681666088935.dkr.ecr.eu-west-1.amazonaws.com/${RELEASE_NAME} .
          docker images
        env:
          RELEASE_NAME: ${{ steps.be_tag.outputs.be_tag }}

      # - uses: mr-smithers-excellent/docker-build-push@v6
      #   name: Build & push Docker image
      #   with:
      #     image: repo/image
      #     tags: v1, latest
      #     registry: registry-url.io
      #     dockerfile: Dockerfile.ci
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
