name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registry-type: private

      # TODO: change set-output - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%dT%H%M%S")"

      # - name: Get ECR path
      #   id: ecr-path
      #   run: echo "::set-output name=registry::681666088935.dkr.ecr.eu-west-1.amazonaws.com"

      # TODO: rationalise these outputs, remove duplication of repository name
      - name: Get Frontend tag
        id: fe_tag
        run: echo "::set-output name=fe_tag::ecr_dev_ops_basics_frontend:main-${{ steps.timestamp.outputs.timestamp }}"

      - name: Get Backend tag
        id: be_tag
        run: echo "::set-output name=be_tag::ecr_dev_ops_basics_backend:main-${{ steps.timestamp.outputs.timestamp }}"

      - name: Build frontend
        working-directory: ./frontend
        run: |
          docker build -t $ECR_REGISTRY/${RELEASE_NAME} .
          docker images
          docker push $ECR_REGISTRY/$RELEASE_NAME
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          RELEASE_NAME: ${{ steps.fe_tag.outputs.fe_tag }}

      - name: Build backend
        working-directory: ./backend
        run: |
          docker build -t $ECR_REGISTRY/${RELEASE_NAME} .
          docker images
          docker push $ECR_REGISTRY/$RELEASE_NAME
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          RELEASE_NAME: ${{ steps.be_tag.outputs.be_tag }}

      - name: Install CDK
        run: |
          npm install -g aws-cdk
          cdk --version

      - name: Deploy to AWS
        working-directory: ./iac
        run: |
          npm install
          cdk diff
          # cdk deploy --require-approval=never
