name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +"%Y%m%dT%H%M%S")"

      - name: Build frontend
        run: |
          cd frontend
          docker build -t 681666088935.dkr.ecr.eu-west-1.amazonaws.com/${RELEASE_NAME} .
          docker images
        env:
          RELEASE_NAME: fe_dev_ops_basics:main-${{ steps.timestamp.outputs.timestamp }}

      - name: Build backend
        run: |
          cd backend
          docker build -t 681666088935.dkr.ecr.eu-west-1.amazonaws.com/${RELEASE_NAME} .
          docker images
        env:
          RELEASE_NAME: be_dev_ops_basics:main-${{ steps.timestamp.outputs.timestamp }}

      # - uses: mr-smithers-excellent/docker-build-push@v6
      #   name: Build & push Docker image
      #   with:
      #     image: repo/image
      #     tags: v1, latest
      #     registry: registry-url.io
      #     dockerfile: Dockerfile.ci
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
